config/routes.rb
Rails.application.routes.draw do
  resources :comments

  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories

  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  get 'home/index'
	resources :posts
	resources :categories
	get 'about', to: 'pages#about'
	get 'contact', to: 'pages#contact'
	get 'resources', to: 'pages#resources'

	root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
		 
  has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  
  validates :name, :email, :body, presence: { message: 'Please fill in' }
  validates :name, length: { minimum: 2, maximum: 20 }
  validates :body, length: { maximum: 500 }
  validates :email, email: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :admin_user
	has_many :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :all_categories
  helper_method :all_posts  
  before_filter :site_search
   
  def all_categories
	@categories = Category.all
  end
  def all_posts
	@posts = Post.all
  end
  def site_search
	@q = Post.ransack(params[:q])
	@q_posts = @q.result(distinct: true)
  end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
	@categories = Category.all
	end
	
	def show
	@category = Category.find(params[:id])
	@title = @category.name
	@posts = @category.posts
	end
	
	private
	def category_params
		params.require(:category).permit(:name)		
	end
end 

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  def create
	@comment = Comment.new(comment_params)
	
	@comment.save
	
	
	respond_to do |format|
		format.js
	end		
  end
  
  private

    def comment_params
      params.require(:comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	@posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController	
	def index
		@q = Post.ransack(params[:q])
		@posts = @q.result(distinct: true)
	end	
	def show
		@post = Post.find(params[:id])
		@user = AdminUser.all
		@comment = Comment.new(:post => @post)
	end
	def new
		@post = Post.new
		@category = Category.all
	end
	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to posts_path, :notice => "Your posts has been saved"
		else
			render "new"
		end
	end	
	def edit
		@post = Post.find(params[:id])
	end				
	def update	
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			redirect_to post_path, :notice => "Your post has been updated"
		else
			render "edit"
		end
	end	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "Your post has been deleted"
	end
	
	private
	def post_params
		params.require(:post).permit(:title, :body, :category_id, :admin_user_id)	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/index.html.erb
<div class="post">
	<h1>Listing categories</h1>
	<ul>
	<% @categories.each do |category| %>
		<li><%= link_to category.name, category %></li>
	<% end %>
	</ul>
</div>

app/views/categories/show.html.erb
<h1><%=@category.name %></h1>
<% if @posts.each do |post| %>
	<div class="post">
		<h2><%= link_to post.title,post %></h2>
		<div class="entry"><%= post.body %></div>
		<div class="byline">
			<p class="meta"><%= post.created_at.strftime("%d %B %Y") %> Posted by <%= post.admin_user.name %></p>
			<p class="links"><%= link_to "Read More",post %></p>
		</div>
	</div>
<% end.empty? %>
	<div class="post">
		<p>Sorry, there are no posts in this category</p>
	</div>
<% end %>
<p><%= link_to "Back to Categories", categories_path %></p>

app/views/comments/create.js.erb
<% if @comment.new_record?  %>
$('#form_div').html('<%= j(render partial:'partials/form', locals: {comment: @comment}) %>');

<% else %>
$('#comment_div').html('<%= j(render partial:'partials/comment', locals: {post: @comment.post}) %>');
$('#form_div').html('<%= j(render partial:'partials/form', locals: {comment: Comment.new(post: @comment.post)}) %>');

<% end %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
	<div class="post">
		<h2 class="blue"><%= link_to post.title,post %></h2>
		<div class="entry"><%= post.body %></div>
		<div class="byline">
			<div class="meta">Posted by <span style="color: #3D9AD2"><%= post.admin_user.try(:name) %></span></div>
			<div class="links"><%= link_to "Read More",post %></div><br />
			<div><%= post.created_at.strftime("%d %B %Y") %></div>
       </div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
					<div class="flash_message">
						<% flash.each do |key,value| %>
							<p><%= value %></p>
						<% end %>
					</div>				
					<%= yield %><!--main view-->	  
					<div style="clear: both;">&nbsp;</div>
				</div>
				<!-- end #content -->  
				<%= render "partials/sidebar" %>
				<div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page-->
	<div id="footer">
		<p>&Copy: 2016, MyApp -Sample Project</p>
	</div>
	<!-- en #footer-->
</div>
<!-- end #wrapper-->

</body>
</html>

app/views/pages/about.html.erb
<div class="post">
	<h1>About MyApp</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sit amet elementum mauris, vel condimentum velit. Donec tincidunt quam rutrum enim ultrices, sit amet sagittis justo euismod. In blandit erat a accumsan dignissim. Aliquam eget libero vel urna sagittis pulvinar efficitur non nibh. Nulla fermentum scelerisque nunc sed rhoncus. Suspendisse at malesuada eros. Vivamus viverra justo at dolor vestibulum, non tempus ipsum semper. Nam fermentum id nibh sit amet suscipit. Etiam ut venenatis sapien. Nam et imperdiet ex.</p>
	<p>Maecenas congue convallis lacus et convallis. Sed gravida vitae enim quis suscipit. Sed auctor malesuada enim, at cursus urna gravida ornare. Mauris sagittis, est eu dapibus ultrices, tellus nulla cursus ex, id consectetur odio quam ac ex. Mauris facilisis enim ac libero porta, ut aliquam arcu lacinia. Pellentesque fermentum odio sit amet arcu tincidunt ornare. Sed eget egestas ex.</p>
	<p>Fusce in tempor leo. Vivamus laoreet, felis in faucibus mattis, erat diam ornare nibh, at dapibus nunc mi id lacus. Mauris eu quam vel mi sollicitudin porttitor sit amet vel ipsum. Nam nisi nisl, dapibus eget dignissim a, cursus ac lectus. Sed purus sapien, mollis at egestas sit amet, euismod in urna. Duis facilisis libero at pellentesque tincidunt. Morbi malesuada pharetra lacinia. Donec eget velit id augue mollis fringilla sed a quam. Proin finibus, odio at lobortis dignissim, quam erat efficitur urna, et scelerisque erat nibh auctor enim. In lobortis magna purus, eu ornare sem blandit a. Sed sed ultricies lectus. Proin eget nisl leo. Curabitur porta vulputate massa, a pretium nulla vehicula eu. Nulla vel magna a magna vulputate bibendum. Donec consequat rhoncus aliquet.</p>
</div>

app/views/pages/contact.html.erb
<div class="post">
	<h1>Contact us</h1><br />
		
	<h3>NRDC Headquarters</h3>
	<p>Natural Resources Defense Council:<br/>
	40 West 20th Street<br/>
	New York, NY 10011</p>

	<p>Telephone: (212) 727-2700<br/>
	Fax: (212) 727-1773</p>

	<h3>NRDC Offices</h3>
	<h4>Washington, DC</h4>
	<p>1152 15th Street NW, Suite 300<br/>
	Washington, DC 20005<br/>
	202-289-6868</p>

	<h4>Midwest</h4>
	<p>20 N. Wacker Drive, Suite 1600<br/>
	Chicago, IL 60606<br/>
	312-663-9900</p>

	<h4>Northern Rockies</h4>
	<p>317 East Mendenhall Street, Suites D &amp; E<br/>
	Bozeman, MT 59715<br/>
	406-556-9300</p>

	<h4>San Francisco, CA</h4>
	<p>111 Sutter St., 21th floor<br/>
	San Francisco, CA 94104<br/>
	415-875-6100</p>

	<h4>Los Angeles, CA</h4>
	<p>1314 Second Street<br/>
	Santa Monica, CA 90401<br/>
	310-434-2300</p>

	<h4>Beijing, China</h4>
	<p>Taikang Financial Tower, Suite 1706, Block 1<br/>
	No.38 East 3rd Ring Road, Chaoyang District<br/>
	Beijing 100026, P.R. China<br/>
	86-10-5927-0688</p>
</div>

app/views/pages/resources.html.erb
<div class="post">
	<h1>Resources</h1><br />
	<ul>
		<li><a href="https://www.google.bg">Social Media Success Metrics</a></li>
		<li><a href="https://www.google.bg">Marketer's Toolkit</a></li>
		<li><a href="https://www.google.bg">AMA's Marketing Resource Directory</a></li>
		<li><a href="https://www.google.bg">White Papers</a></li>
		<li><a href="https://www.google.bg">Research Reports</a></li>
		<li><a href="https://www.google.bg">Case Studies</a></li>
		<li><a href="https://www.google.bg">Best Practices</a></li>
		<li><a href="https://www.google.bg">Specialized Directories</a></li>
	</ul>	
</div>

app/views/partials/_comment.html.erb
<h3> Comments (<%= post.comments.count %>)</h3>
<% post.comments.each do |comment| %>
<div class="comment_container">
	<i class="comment_name"><%= comment.name %>:</i>
	<div class="comment_body"><%= comment.body %></div>
</div>
<% end %>

app/views/partials/_form.html.erb
<%= form_for comment, remote: true do |f| %>
	<%= f.hidden_field :post_id %>
	<p>		
		<%= f.text_field :name, placeholder: 'Name', required: true %>
		<%= f.error_message_on :name %>
	</p>
	
	<p>
		<%= f.text_field :email, placeholder: 'Email', required: true %>
		<%= f.error_message_on :email %>
	</p>
	
	<p>
		<%= f.text_area :body, placeholder: 'Comment', required: true %>
		<%= f.error_message_on :body %>
	</p>
	
	<p>
		<%= f.submit "Post Comment" %>
	</p>	
<% end %>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Abel" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1 id="logo_text"><%= link_to "My Ruby Blog",root_path %></h1>
				<p>Learning Ruby on Rails</p>
			</div>
			<div id="menu">
				<ul class="main_nav">
					<li><%= link_to "Home",root_path %></li>
					<li><%= link_to "About",about_path %></li>
					<li><%= link_to "Blog",posts_path %></li>
					<li><%= link_to "Contact",contact_path %></li>
					<li><%= link_to "Resources",resources_path %></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- end #header -->

app/views/partials/_sidebar.html.erb
<div id="sidebar">
	<ul>
		<li>
			<div id="search">
				<%= search_form_for @q do |f| %>
					<%= f.text_field :title_or_body_cont %>
					<%= f.submit "GO" %>
				<% end  %>
			</div>﻿
			<div style="clear: both;">&nbsp;</div>
		</li>
		<li>
			<h2>Get The Framework</h2>
			<p>You can download Ruby and Ruby on Rails for free right now
			<a style="color:#d02552; text-decoration:none" href="http://rubyonrails.org/">here</a></p>
		</li>
		<li>
			<h2><%= link_to "Categories", categories_path %></h2>
			<ul>
				<% all_categories.each do |cat| %>
					<li><%= link_to cat.name,category_path(:id => cat.id) %></li>
				<% end %>
			</ul>
		</li>
		<li>
			<h2><%= link_to "Blogroll", posts_path %></h2>
			<ul>
				<% all_posts.each do |post| %>
					<li><%= link_to post.title,post_path(:id => post.id) %></li>
				<% end %>
			</ul>
		</li>

	</ul>
</div>
<!-- end #sidebar -->

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post">
		<h2 class="blue"><%= link_to post.title,post %></h2>
		<div class="entry"><%= post.body %></div>
		<div class="byline">
			<div class="meta">Posted by <span style="color: #3D9AD2"><%= post.admin_user.try(:name) %></span></div>
			<div class="links"><%= link_to "Read More",post %></div><br />
			<div><%= post.created_at.strftime("%d %B %Y") %></div>
       </div>
	</div>
<% end %>

app/views/posts/show.html.erb
<div class="post">
	<h1><%= @post.title %></h1>
	<small><%= @post.created_at.strftime("%d %B %Y") %></small>
	<p>Posted by <span style="color: #3D9AD2"><%= @post.admin_user.try(:name) %></span></p>
	<p style="white-space: pre-wrap;"><%= @post.body %></p>
	<p>Category:
		<% if @post.category %>
			<%= link_to @post.category.name, category_path(:id => @post.category.id) %>
		<% else %>
			<span>None</span>
		<% end %>
	</p>
	<p><%= link_to "Back to Blog Posts", posts_path %></p>
    <div id='comment_div'>
		<%= render partial: 'partials/comment', locals: { post: @post } %>
	</div>
	<h3>Add a Comment</h3>
	<div id='form_div'>
		<%= render partial: 'partials/form', locals: { comment: @comment } %>
	</div>
</div>